config:
  aws:region: us-east-1
  code-remote:gemini_model: gemini-2.5-flash
  code-remote:neo4j_uri: neo4j+ssc://3cbaec73.databases.neo4j.io:7687
  code-remote:neo4j_password:
    secure: AAABAMsLgnbkY3U2y5E2gNauVlmjZhUIRt358fHjghdmVVrzt2NmwgSSa+THtKoELwtpA5gZPPJXI9pnDtLOhFzXPncbm+1GlDjc
