"""Sync event schemas for Neo4j synchronization."""

from datetime import UTC, datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    """Get current UTC time in a timezone-aware format."""
    return datetime.now(UTC)


class SnippetSyncEvent(BaseModel):
    """Event sent to SQS when a snippet needs to be synced to Neo4j.

    Events are triggered by:
    - snippet.analyzed: After code analysis completes (upsert to Neo4j)
    - snippet.deleted: After snippet deletion (remove from Neo4j)
    """

    event_type: Literal["snippet.analyzed", "snippet.deleted"] = Field(
        description="Type of sync event"
    )
    snippet_id: UUID = Field(description="UUID of the snippet")
    user_id: UUID = Field(description="UUID of the snippet owner")
    timestamp: datetime = Field(default_factory=_utc_now, description="When the event occurred")

    def to_sqs_message(self) -> dict:
        """Convert to SQS message format.

        Returns:
            Dictionary suitable for SQS send_message.
        """
        return {
            "MessageBody": self.model_dump_json(),
            "MessageGroupId": str(self.snippet_id),  # FIFO ordering by snippet
            # MessageDeduplicationId is auto-generated by content-based dedup
        }

    @classmethod
    def analyzed(cls, snippet_id: UUID, user_id: UUID) -> "SnippetSyncEvent":
        """Create an analyzed event.

        Args:
            snippet_id: UUID of the snippet.
            user_id: UUID of the owner.

        Returns:
            SnippetSyncEvent instance.
        """
        return cls(
            event_type="snippet.analyzed",
            snippet_id=snippet_id,
            user_id=user_id,
        )

    @classmethod
    def deleted(cls, snippet_id: UUID, user_id: UUID) -> "SnippetSyncEvent":
        """Create a deleted event.

        Args:
            snippet_id: UUID of the snippet.
            user_id: UUID of the owner.

        Returns:
            SnippetSyncEvent instance.
        """
        return cls(
            event_type="snippet.deleted",
            snippet_id=snippet_id,
            user_id=user_id,
        )
